POST http://localhost:3333/videos
content-type: application/json

{
    "title": "estudo",
    "description": "Video de Node.js",
    "duration": 30
}

###
GET http://localhost:3333/videos

###
PUT http://localhost:3333/videos/9e58d8d5-365b-43e0-a280-a7467e7f2067
content-type: application/json

{
    "title": "Video Node.js",
    "description": "Aula de como comecar no Node.js",
    "duration": 121
}

###

DELETE  http://localhost:3333/videos/5a0f851c-2be7-4bc6-8433-260563607bec
