POST http://localhost:3333/videos
content-type: application/json

{
    "title": "Video node",
    "description": "Video de Node.js",
    "duration": 90
}

###
GET http://localhost:3333/videos?search=node

###
PUT http://localhost:3333/videos/0c4cd4c7-2069-47da-b711-bea7b2d3c0fa
content-type: application/json

{
    "title": "Video 02",
    "description": "Video de React.js",
    "duration": 180
}

###

DELETE  http://localhost:3333/videos/1e6d2d79-dfd6-4c6f-9c4c-c3b33a542085